using System.Collections.Generic;
using System.Text;

namespace Credfeto.DotNet.Repo.Tools.TemplateUpdate.Tests.Services;

internal sealed class LabelsYamlBuilder
{
    private readonly List<(string Name, string Color, string Description)> _labels = [];

    public LabelsYamlBuilder Add(string name, string color, string description)
    {
        this._labels.Add((name, color, description));

        return this;
    }

    public string Build()
    {
        StringBuilder sb = new StringBuilder()
            .AppendLine("---")
            .AppendLine("# Defines the labels available in this GitHub repository.")
            .AppendLine("# Generated by credfeto-dotnet-repo-tools");

        bool first = true;

        foreach ((string name, string color, string description) in this._labels)
        {
            if (!first)
            {
                sb = sb.AppendLine();
            }

            first = false;

            sb = sb.AppendLine($"- name: \"{name}\"").AppendLine($"  color: \"{color}\"");

            if (!string.IsNullOrWhiteSpace(description))
            {
                sb = sb.AppendLine($"  description: \"{description}\"");
            }
        }

        return sb.ToString();
    }
}
