using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Credfeto.DotNet.Repo.Tools.TemplateUpdate.Tests.Services;

internal sealed class LabelerYamlBuilder
{
    private readonly List<(string Name, string[] Paths)> _entries = [];

    public LabelerYamlBuilder Add(string name, params string[] paths)
    {
        this._entries.Add((name, paths));

        return this;
    }

    public string Build()
    {
        StringBuilder sb = new StringBuilder()
            .AppendLine("---")
            .AppendLine(
                "# Configures the GitHub Pull Request Labeler - applies labels to pull requests based on changed files."
            )
            .AppendLine("# Generated by credfeto-dotnet-repo-tools");

        foreach ((string name, string[] paths) in this._entries)
        {
            string pathList = string.Join(separator: ", ", paths.Select(p => $"'{p}'"));
            sb = sb.AppendLine($"\"{name}\":").AppendLine($"  - any: [{pathList}]");
        }

        return sb.ToString();
    }
}
