using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Credfeto.DotNet.Repo.Tools.TemplateUpdate.Tests.Services;

internal sealed class LabelerYamlBuilder
{
    private readonly List<(string Name, string[] Paths)> _entries = [];

    public LabelerYamlBuilder Add(string name, params string[] paths)
    {
        this._entries.Add((name, paths));

        return this;
    }

    public string Build()
    {
        StringBuilder labelerYaml = new StringBuilder()
            .AppendLine(
                "--- # Configures the GitHub Pull Request Labeler - applies labels to pull requests based on changed files."
            )
            .AppendLine("# Generated by credfeto-dotnet-repo-tools");

        foreach ((string name, string[] paths) in this._entries)
        {
            labelerYaml = labelerYaml.AppendLine($"\"{name}\":").AppendLine($"  - any: [{FormatPathList(paths)}]");
        }

        return labelerYaml.ToString();
    }

    private static string FormatPathList(string[] paths)
    {
        return string.Join(separator: ", ", paths.Select(p => $"'{p}'"));
    }
}
